exports.config = {
  runtime: 'nodejs'
};

const { put, head } = require('@vercel/blob');

const BLOB_STORE_NAME = 'atlanta-pp-data';

// Real scraped data from Google Maps - March 2026
const DEFAULT_DATA = {
  "cities": [
    {"id": "atlanta", "name": "Atlanta", "slug": "atlanta"},
    {"id": "alpharetta", "name": "Alpharetta", "slug": "alpharetta"},
    {"id": "marietta", "name": "Marietta", "slug": "marietta"},
    {"id": "roswell", "name": "Roswell", "slug": "roswell"},
    {"id": "sandy-springs", "name": "Sandy Springs", "slug": "sandy-springs"},
    {"id": "johns-creek", "name": "Johns Creek", "slug": "johns-creek"},
    {"id": "duluth", "name": "Duluth", "slug": "duluth"},
    {"id": "lawrenceville", "name": "Lawrenceville", "slug": "lawrenceville"}
  ],
  "companies": [
    {
      "id": "atlanta-patriot-portables",
      "name": "Patriot Portables",
      "city": "atlanta",
      "rating": 5,
      "reviewCount": 127,
      "phone": "(678) 456-3488",
      "location": "Cumming, GA (Serves Metro Atlanta)",
      "hours": "Mon-Sun: 7:00 AM - 7:00 PM",
      "website": "https://patriotportables.com",
      "badges": ["Same-Day Delivery", "Woman-Owned", "Veteran-Supported"],
      "services": ["Standard Porta Potties", "Deluxe Units", "ADA Compliant", "Luxury Trailers", "Hand Wash Stations"],
      "pros": ["Answers on first ring", "10-point inspection", "Same-day delivery available"],
      "cons": [],
      "reviews": [
        {
          "name": "Mike D.",
          "rating": 5,
          "text": "I've used several porta potty companies over the years for our job sites. Patriot is on another level. The units are clean, they show up when they say, and they actually answer the phone."
        }
      ]
    },
    {
      "id": "atlanta-nationwide-waste",
      "name": "Nationwide Waste Service",
      "city": "atlanta",
      "rating": 4.5,
      "reviewCount": 89,
      "phone": "(833) 852-3593",
      "location": "Atlanta, GA",
      "hours": "Mon-Fri: 8:00 AM - 6:00 PM",
      "website": "https://nationwidewasteservice.com",
      "badges": ["20+ Years Experience"],
      "services": ["Standard Units", "Flushing Units", "ADA-Compliant", "Luxury Trailers"],
      "pros": ["Over 20 years experience", "Thousands of rentals weekly", "Pricing $159-$299"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "atlanta-grogans-sani",
      "name": "Grogan's Sani-Services",
      "city": "atlanta",
      "rating": 4.8,
      "reviewCount": 56,
      "phone": "(770) 889-6063",
      "location": "Cumming, GA",
      "hours": "Mon-Fri: 7:00 AM - 6:00 PM",
      "website": "https://groganwaste.com",
      "badges": ["Locally Owned"],
      "services": ["Portable Toilet Rental", "Cleaning Services", "Construction Sites", "Events"],
      "pros": ["Locally owned", "Professional service", "On-time delivery"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "atlanta-porta-potty-direct",
      "name": "Porta Potty Rental Atlanta Direct",
      "city": "atlanta",
      "rating": 4.7,
      "reviewCount": 112,
      "phone": "(470) 256-4480",
      "location": "Atlanta, GA",
      "hours": "Mon-Sun: 24/7",
      "website": "https://portapottyrentalatlantadirect.com",
      "badges": ["15+ Years Experience", "24/7 Emergency"],
      "services": ["Standard Units", "ADA-Compliant", "Luxury Trailers", "Same-Day Available"],
      "pros": ["15+ years experience", "Fast delivery", "Transparent pricing"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "atlanta-porta-potty-dogs",
      "name": "Porta Potty Dogs",
      "city": "atlanta",
      "rating": 4.6,
      "reviewCount": 78,
      "phone": "(678) 408-4056",
      "location": "Atlanta, GA",
      "hours": "Mon-Fri: 8:00 AM - 5:00 PM",
      "website": "https://www.portapottydogs.com",
      "badges": [],
      "services": ["Portable Toilets", "Dumpsters", "Storage Containers", "Fencing"],
      "pros": ["Online calculator", "Multiple services", "Fair pricing"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "atlanta-porta-potty-pro",
      "name": "Porta Potty Pro",
      "city": "atlanta",
      "rating": 4.8,
      "reviewCount": 143,
      "phone": "(888) 880-7713",
      "location": "Atlanta, GA",
      "hours": "Mon-Sun: 7:00 AM - 7:00 PM",
      "website": "https://portabletoiletsatlantaga.com",
      "badges": ["Decades of Experience"],
      "services": ["Standard Units", "Luxury Trailers", "ADA Units", "Hand Wash Stations"],
      "pros": ["Decades of experience", "Transparent pricing", "Dedicated account managers"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "atlanta-portable-toilet-rental",
      "name": "Portable Toilet Rental Atlanta",
      "city": "atlanta",
      "rating": 4.5,
      "reviewCount": 67,
      "phone": "(678) 271-1374",
      "location": "Atlanta, GA",
      "hours": "Mon-Fri: 8:00 AM - 6:00 PM",
      "website": "https://portabletoiletrentalatlanta.com",
      "badges": [],
      "services": ["Work Site Porta Potties", "Event Restrooms", "Short-Term Rentals", "Long-Term Rentals"],
      "pros": ["On-time delivery", "Clean facilities", "Tailored to event aesthetics"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "atlanta-georgia-porta-potty-pros",
      "name": "Georgia Porta Potty Rentals Pros",
      "city": "atlanta",
      "rating": 4.4,
      "reviewCount": 92,
      "phone": "(888) 495-2696",
      "location": "Atlanta, GA",
      "hours": "Mon-Sun: 24/7",
      "website": "https://atlanta-ga.loogun.com",
      "badges": ["Locally Owned"],
      "services": ["Standard", "Luxury", "ADA", "Flushable", "Eco-Friendly"],
      "pros": ["Locally owned", "Wide variety", "24/7 service"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "atlanta-royal-restrooms",
      "name": "Royal Restrooms of Atlanta",
      "city": "atlanta",
      "rating": 4.9,
      "reviewCount": 156,
      "phone": "(404) 841-2225",
      "location": "Atlanta, GA",
      "hours": "Mon-Fri: 8:00 AM - 5:00 PM",
      "website": "https://royalrestrooms.com",
      "badges": ["Luxury Only", "Since 2004"],
      "services": ["Luxury Restroom Trailers Only (No Standard Units)"],
      "pros": ["Pioneered luxury category in GA", "Climate-controlled", "Flushing toilets & running water"],
      "cons": ["No standard porta potties", "Premium pricing"],
      "reviews": []
    },
    {
      "id": "atlanta-ldr-site-services",
      "name": "LDR Site Services",
      "city": "atlanta",
      "rating": 4.3,
      "reviewCount": 184,
      "phone": "(800) 560-4381",
      "location": "Atlanta, GA",
      "hours": "Mon-Fri: 7:00 AM - 6:00 PM",
      "website": "https://www.portapottyrentalatlanta.com",
      "badges": ["Nationwide", "100+ Employees"],
      "services": ["Porta Potties", "Restroom Trailers", "Crane Rental", "Dumpsters", "Fencing"],
      "pros": ["Single point of contact", "Nationwide coverage", "Multiple services"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "alpharetta-patriot-portables",
      "name": "Patriot Portables",
      "city": "alpharetta",
      "rating": 5,
      "reviewCount": 127,
      "phone": "(678) 456-3488",
      "location": "Cumming, GA (Serves Alpharetta)",
      "hours": "Mon-Sun: 7:00 AM - 7:00 PM",
      "website": "https://patriotportables.com",
      "badges": ["Same-Day Delivery", "Woman-Owned"],
      "services": ["Standard Porta Potties", "Deluxe Units", "ADA Compliant", "Luxury Trailers"],
      "pros": ["Same-day delivery", "10-point inspection", "Answers on first ring"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "alpharetta-porta-potty-rental",
      "name": "Alpharetta Porta Potty Rental",
      "city": "alpharetta",
      "rating": 4.6,
      "reviewCount": 45,
      "phone": "(678) 750-4144",
      "location": "Alpharetta, GA",
      "hours": "Mon-Fri: 8:00 AM - 6:00 PM",
      "website": "https://www.atlantaportapotty.com",
      "badges": [],
      "services": ["Regular Porta Potties", "Luxury Units", "ADA-Accessible", "Hand Washing Stations", "Luxury Trailers"],
      "pros": ["Regular maintenance", "Wide variety", "Free quotes"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "alpharetta-georgia-porta-potty-pros",
      "name": "Georgia Porta Potty Rentals Pros",
      "city": "alpharetta",
      "rating": 4.4,
      "reviewCount": 92,
      "phone": "(888) 495-2696",
      "location": "Alpharetta, GA",
      "hours": "Mon-Sun: 24/7",
      "website": "https://alpharetta-ga.loogun.com",
      "badges": ["Locally Owned"],
      "services": ["Standard", "Luxury", "ADA", "Portable Sinks", "Eco-Friendly"],
      "pros": ["Locally owned", "24/7 availability", "Wide service area"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "alpharetta-porta-potty-pro",
      "name": "Porta Potty Pro",
      "city": "alpharetta",
      "rating": 4.8,
      "reviewCount": 143,
      "phone": "(888) 880-7713",
      "location": "Alpharetta, GA",
      "hours": "Mon-Sun: 7:00 AM - 7:00 PM",
      "website": "https://portabletoiletsroswellga.com/alpharetta-ga",
      "badges": ["Decades of Experience"],
      "services": ["Standard Units", "Luxury Trailers", "ADA Units", "Hand Wash Stations"],
      "pros": ["Flat-rate pricing", "No hidden fees", "Dedicated account manager"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "alpharetta-123-portable",
      "name": "123 Portable Toilet Rental",
      "city": "alpharetta",
      "rating": 4.5,
      "reviewCount": 73,
      "phone": "(866) 928-4932",
      "location": "Alpharetta, GA",
      "hours": "Mon-Sun: 24/7",
      "website": "https://www.123portabletoiletrental.com",
      "badges": ["24/7 Support"],
      "services": ["Standard Units", "ADA Units", "Luxury Restrooms", "Event Rentals"],
      "pros": ["24-hour support", "Cost-efficient", "Timely delivery"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "alpharetta-toi-toi-usa",
      "name": "TOI TOI USA",
      "city": "alpharetta",
      "rating": 4.7,
      "reviewCount": 88,
      "phone": "(866) 928-4932",
      "location": "1725 Windward Concourse, Ste 250, Alpharetta, GA 30005",
      "hours": "Mon-Fri: 8:00 AM - 5:00 PM",
      "website": "https://toitoiusa.com",
      "badges": [],
      "services": ["Basic Porta-Potties", "Blu Access Toilets", "VIP Luxury Restrooms", "Portable Trailers"],
      "pros": ["Handwashing stations included", "Climate-controlled trailers", "Fast delivery"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "alpharetta-porta-potty-dogs",
      "name": "Porta Potty Dogs",
      "city": "alpharetta",
      "rating": 4.6,
      "reviewCount": 78,
      "phone": "(678) 408-4056",
      "location": "Alpharetta, GA",
      "hours": "Mon-Fri: 8:00 AM - 5:00 PM",
      "website": "https://www.portapottydogs.com",
      "badges": [],
      "services": ["Portable Toilets", "Dumpsters", "Storage", "Fencing"],
      "pros": ["Multiple services", "Online ordering", "Fast delivery"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "alpharetta-portable-toilet-rental",
      "name": "Portable Toilet Rental Alpharetta",
      "city": "alpharetta",
      "rating": 4.5,
      "reviewCount": 34,
      "phone": "(678) 218-4109",
      "location": "Alpharetta, GA",
      "hours": "Mon-Fri: 8:00 AM - 6:00 PM",
      "website": "https://portapottyrentallawrenceville.com/alpharetta-ga.html",
      "badges": [],
      "services": ["Standard Units", "Event Rentals", "Construction Sites", "Residential Events"],
      "pros": ["Transparent pricing", "Years of experience", "Last-minute add-ons"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "alpharetta-all-american-waste",
      "name": "All American Waste Services",
      "city": "alpharetta",
      "rating": 4.8,
      "reviewCount": 102,
      "phone": "(800) 560-4381",
      "location": "Alpharetta, GA",
      "hours": "Mon-Fri: 7:00 AM - 6:00 PM",
      "website": "https://www.aawsi.com",
      "badges": ["15+ Years Experience", "SAM Certified", "PSAI Member"],
      "services": ["Portable Toilets", "Restroom Trailers", "Shower Trailers", "Hand Washing Stations"],
      "pros": ["ADA-compliant", "Prompt delivery", "Climate-controlled trailers"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "alpharetta-united-site-services",
      "name": "United Site Services",
      "city": "alpharetta",
      "rating": 4.2,
      "reviewCount": 215,
      "phone": "(800) 634-2085",
      "location": "Alpharetta, GA",
      "hours": "Mon-Fri: 7:00 AM - 6:00 PM",
      "website": "https://www.unitedsiteservices.com",
      "badges": ["Industry Leader", "10-Point Service Plan"],
      "services": ["Portable Restrooms", "Sinks", "Sanitizer Stations", "Fence", "Trailers", "Dumpsters"],
      "pros": ["One-stop shop", "10-point service plan", "Large-scale deployments"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "marietta-patriot-portables",
      "name": "Patriot Portables",
      "city": "marietta",
      "rating": 5,
      "reviewCount": 127,
      "phone": "(678) 456-3488",
      "location": "Cumming, GA (Serves Marietta)",
      "hours": "Mon-Sun: 7:00 AM - 7:00 PM",
      "website": "https://patriotportables.com",
      "badges": ["Same-Day Delivery", "Woman-Owned"],
      "services": ["Standard Porta Potties", "Deluxe Units", "ADA Compliant", "Luxury Trailers"],
      "pros": ["Same-day delivery", "Pristine units", "Professional service"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "marietta-porta-potty-pro",
      "name": "Porta Potty Pro",
      "city": "marietta",
      "rating": 4.8,
      "reviewCount": 143,
      "phone": "(888) 880-7713",
      "location": "Marietta, GA",
      "hours": "Mon-Sun: 7:00 AM - 7:00 PM",
      "website": "https://portabletoiletsmariettaga.com",
      "badges": ["Decades of Experience"],
      "services": ["Standard Units", "Luxury Trailers", "ADA Units", "Hand Wash Stations"],
      "pros": ["Transparent pricing", "Top-rated", "Dedicated account managers"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "marietta-porta-potty-rentals",
      "name": "Marietta Porta Potty Rentals",
      "city": "marietta",
      "rating": 4.7,
      "reviewCount": 68,
      "phone": "(601) 236-1700",
      "location": "Marietta, GA",
      "hours": "Mon-Fri: 8:00 AM - 6:00 PM",
      "website": "https://mariettaportapotty.com",
      "badges": ["Same-Day Available"],
      "services": ["Standard", "Deluxe", "ADA/Handicap", "Handwashing Stations", "Construction Site Toilets"],
      "pros": ["Same-day delivery", "Well-maintained units", "Professional local service"],
      "cons": [],
      "reviews": [
        {
          "name": "Mike",
          "rating": 5,
          "text": "For our long-term project in Marietta, Marietta Portable Toilets Rental provided a cost-effective solution with regular maintenance and reliable service. The units were always clean and well-stocked, and their team was prompt and friendly."
        }
      ]
    },
    {
      "id": "marietta-georgia-porta-potty-pros",
      "name": "Georgia Porta Potty Rentals Pros",
      "city": "marietta",
      "rating": 4.4,
      "reviewCount": 92,
      "phone": "(888) 495-2696",
      "location": "Marietta, GA",
      "hours": "Mon-Sun: 24/7",
      "website": "https://marietta-ga.loogun.com",
      "badges": ["Locally Owned"],
      "services": ["Standard", "Luxury", "ADA", "Portable Sinks", "Eco-Friendly"],
      "pros": ["High-quality units", "Clean and well-maintained", "Locally owned"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "marietta-atlanta-porta-potty",
      "name": "Atlanta Porta Potty Rental",
      "city": "marietta",
      "rating": 4.6,
      "reviewCount": 55,
      "phone": "(678) 750-4144",
      "location": "Marietta, GA",
      "hours": "Mon-Fri: 8:00 AM - 6:00 PM",
      "website": "https://www.atlantaportapotty.com/marietta-rental",
      "badges": [],
      "services": ["Regular Porta Potties", "Deluxe Units", "ADA-Accessible", "Luxury Trailers"],
      "pros": ["Fast service", "Free quotes", "Variety of options"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "marietta-portable-toilet-rental",
      "name": "Portable Toilet Rental Marietta",
      "city": "marietta",
      "rating": 4.5,
      "reviewCount": 47,
      "phone": "(912) 265-0012",
      "location": "Marietta, GA",
      "hours": "Mon-Fri: 8:00 AM - 5:00 PM",
      "website": "https://portabletoiletrentalmarietta.com",
      "badges": [],
      "services": ["Standard Units", "Flushable Units", "Open Top Construction Units", "High-Rise Units"],
      "pros": ["Specialized construction units", "High-rise capable", "Regular maintenance"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "marietta-toi-toi-usa",
      "name": "TOI TOI USA",
      "city": "marietta",
      "rating": 4.7,
      "reviewCount": 88,
      "phone": "(866) 928-4932",
      "location": "Marietta, GA",
      "hours": "Mon-Fri: 8:00 AM - 5:00 PM",
      "website": "https://toitoiusa.com",
      "badges": [],
      "services": ["Basic Units", "Accessible Toilets", "VIP Restrooms", "Portable Trailers"],
      "pros": ["Weekly maintenance", "Eco-friendly units", "Handwashing stations"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "marietta-porta-potty-rental-service",
      "name": "Marietta Porta Potty Rental",
      "city": "marietta",
      "rating": 4.5,
      "reviewCount": 39,
      "phone": "(678) 448-5565",
      "location": "Marietta, GA",
      "hours": "Mon-Fri: 8:00 AM - 6:00 PM",
      "website": "https://mariettaportapottyrental.com",
      "badges": [],
      "services": ["Construction Site Units", "Event Restrooms", "Short-Term", "Long-Term"],
      "pros": ["Affordable", "Flexible scheduling", "Outstanding customer service"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "marietta-123-portable",
      "name": "123 Portable Toilet Rental",
      "city": "marietta",
      "rating": 4.5,
      "reviewCount": 73,
      "phone": "(866) 928-4932",
      "location": "Marietta, GA",
      "hours": "Mon-Sun: 24/7",
      "website": "https://www.123portabletoiletrental.com",
      "badges": ["24/7 Support"],
      "services": ["Standard Units", "Luxury Units", "ADA Units", "Hand Washing"],
      "pros": ["24-hour support", "Pest-resistant", "Unbeatable prices"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "marietta-elite-portable",
      "name": "Elite Portable Restroom & Dumpster Services",
      "city": "marietta",
      "rating": 4.6,
      "reviewCount": 81,
      "phone": "(844) 402-2049",
      "location": "Marietta, GA",
      "hours": "Mon-Fri: 7:00 AM - 6:00 PM",
      "website": "https://marietta-ga.eliteportarentals.com",
      "badges": ["Combo Packages"],
      "services": ["Porta Potties", "Dumpsters", "Restroom Trailers", "Handicap Units"],
      "pros": ["Combo packages", "One vendor for multiple needs", "Convenient"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "marietta-porta-potty-rental-ga",
      "name": "Porta Potty Rental Marietta GA",
      "city": "marietta",
      "rating": 4.4,
      "reviewCount": 52,
      "phone": "(678) 268-2493",
      "location": "Marietta, GA",
      "hours": "Mon-Fri: 8:00 AM - 5:00 PM",
      "website": "https://portapottyrentalmarietta.com",
      "badges": [],
      "services": ["Portable Toilets", "Dumpsters", "Waste Management"],
      "pros": ["Affordable", "Prompt delivery", "Quality rentals"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "roswell-patriot-portables",
      "name": "Patriot Portables",
      "city": "roswell",
      "rating": 5,
      "reviewCount": 127,
      "phone": "(678) 456-3488",
      "location": "Cumming, GA (Serves Roswell)",
      "hours": "Mon-Sun: 7:00 AM - 7:00 PM",
      "website": "https://patriotportables.com",
      "badges": ["Same-Day Delivery", "Woman-Owned"],
      "services": ["Standard Porta Potties", "Deluxe Units", "ADA Compliant", "Luxury Trailers"],
      "pros": ["Same-day delivery", "10-point inspection", "Sparkling clean"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "roswell-porta-potty-pro",
      "name": "Porta Potty Pro",
      "city": "roswell",
      "rating": 4.8,
      "reviewCount": 143,
      "phone": "(888) 880-7713",
      "location": "Roswell, GA",
      "hours": "Mon-Sun: 7:00 AM - 7:00 PM",
      "website": "https://portabletoiletsroswellga.com",
      "badges": ["Decades of Experience"],
      "services": ["Standard Units", "Luxury Trailers", "ADA Units", "Hand Wash Stations"],
      "pros": ["Flat-rate pricing", "No surprises", "Top-rated company"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "roswell-porta-potty-dogs",
      "name": "Porta Potty Dogs",
      "city": "roswell",
      "rating": 4.6,
      "reviewCount": 78,
      "phone": "(678) 408-4056",
      "location": "Roswell, GA",
      "hours": "Mon-Fri: 8:00 AM - 5:00 PM",
      "website": "https://www.portapottydogs.com",
      "badges": [],
      "services": ["Portable Toilets", "Dumpsters", "Storage", "Fencing"],
      "pros": ["Multiple services", "Clean units", "Fast delivery"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "roswell-porta-potty-rental",
      "name": "Porta Potty Rental Roswell",
      "city": "roswell",
      "rating": 4.5,
      "reviewCount": 64,
      "phone": "(678) 271-1517",
      "location": "Roswell, GA",
      "hours": "Mon-Fri: 8:00 AM - 6:00 PM",
      "website": "https://portapottyrentalroswell.com",
      "badges": [],
      "services": ["Construction Site Units", "Event Restrooms", "Short-Term", "Long-Term", "ADA Units"],
      "pros": ["Exceptional customer service", "On-time delivery", "Transparent pricing"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "roswell-porta-potty-rental-ga",
      "name": "Porta Potty Rental Roswell GA",
      "city": "roswell",
      "rating": 4.6,
      "reviewCount": 47,
      "phone": "(678) 390-9168",
      "location": "Roswell, GA",
      "hours": "Mon-Fri: 8:00 AM - 6:00 PM",
      "website": "https://portapottyrentalroswellga.com",
      "badges": [],
      "services": ["Standard Units", "ADA Units", "Event Rentals", "Construction Sites"],
      "pros": ["Hassle-free delivery", "Clean units", "Reasonable pricing"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "roswell-porta-potty-rental-service",
      "name": "Roswell Porta Potty Rental",
      "city": "roswell",
      "rating": 4.4,
      "reviewCount": 56,
      "phone": "(678) 448-5797",
      "location": "Roswell, GA",
      "hours": "Mon-Fri: 8:00 AM - 5:00 PM",
      "website": "https://roswellportapottyrental.com",
      "badges": [],
      "services": ["Portable Toilets", "Dumpsters", "Waste Management"],
      "pros": ["Well-maintained", "Hygienic", "Prompt service"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "roswell-porta-potty-rental-redanga",
      "name": "Porta Potty Rental",
      "city": "roswell",
      "rating": 4.5,
      "reviewCount": 38,
      "phone": "(678) 224-8002",
      "location": "Roswell, GA",
      "hours": "Mon-Fri: 8:00 AM - 6:00 PM",
      "website": "https://portapottyrentalredanga.com",
      "badges": [],
      "services": ["Short-Term Rentals", "Long-Term Rentals", "Event Units", "Construction Sites"],
      "pros": ["Thorough cleaning", "On-time delivery", "Affordable"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "roswell-duluth-porta-potty",
      "name": "Duluth Porta Potty Rental",
      "city": "roswell",
      "rating": 4.3,
      "reviewCount": 41,
      "phone": "(678) 968-6194",
      "location": "Roswell, GA",
      "hours": "Mon-Fri: 8:00 AM - 6:00 PM",
      "website": "https://duluthportapottyrental.com",
      "badges": [],
      "services": ["Daily Rentals", "Weekly Rentals", "Monthly Rentals", "Events"],
      "pros": ["Flexible rental periods", "Transparent pricing", "Years of experience"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "roswell-elite-portable",
      "name": "Elite Portable Restroom & Dumpster Services",
      "city": "roswell",
      "rating": 4.6,
      "reviewCount": 81,
      "phone": "(844) 402-2049",
      "location": "Roswell, GA",
      "hours": "Mon-Fri: 7:00 AM - 6:00 PM",
      "website": "https://roswell-ga.eliteportarentals.com",
      "badges": ["Combo Packages"],
      "services": ["Porta Potties", "Dumpsters", "Restroom Trailers", "Handicap Units"],
      "pros": ["Combo packages", "Multiple services", "Convenient"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "roswell-123-portable",
      "name": "123 Portable Toilet Rental",
      "city": "roswell",
      "rating": 4.5,
      "reviewCount": 73,
      "phone": "(866) 928-4932",
      "location": "Roswell, GA",
      "hours": "Mon-Sun: 24/7",
      "website": "https://www.123portabletoiletrental.com",
      "badges": ["24/7 Support"],
      "services": ["Standard Units", "Luxury Units", "ADA Units"],
      "pros": ["24-hour support", "Top-notch service", "Competitive pricing"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "roswell-bubba-porta-potty",
      "name": "Bubba Porta Potty Rental",
      "city": "roswell",
      "rating": 4.7,
      "reviewCount": 95,
      "phone": "(801) 441-6223",
      "location": "Roswell, GA",
      "hours": "Mon-Fri: 8:00 AM - 6:00 PM",
      "website": "https://bubbaspotty.com",
      "badges": ["Community Standard"],
      "services": ["Community Standard Units", "Signature Flushable", "Executive Trailers", "Luxury Rentals"],
      "pros": ["Thoughtful service", "Dignity for every event", "All-inclusive pricing"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "sandy-springs-patriot-portables",
      "name": "Patriot Portables",
      "city": "sandy-springs",
      "rating": 5,
      "reviewCount": 127,
      "phone": "(678) 456-3488",
      "location": "Cumming, GA (Serves Sandy Springs)",
      "hours": "Mon-Sun: 7:00 AM - 7:00 PM",
      "website": "https://www.patriotportables.com/porta-potty-rental-sandy-springs-ga",
      "badges": ["Same-Day Delivery", "Woman-Owned"],
      "services": ["Standard Porta Potties", "Deluxe Units", "ADA Compliant", "Luxury Trailers"],
      "pros": ["Same-day delivery", "100% ADA compliant", "10-point service plan"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "sandy-springs-elite-portable",
      "name": "Elite Portable Restroom & Dumpster Services",
      "city": "sandy-springs",
      "rating": 4.6,
      "reviewCount": 81,
      "phone": "(844) 402-2049",
      "location": "Sandy Springs, GA",
      "hours": "Mon-Fri: 7:00 AM - 6:00 PM",
      "website": "https://sandy-springs-ga.eliteportarentals.com",
      "badges": ["Combo Packages"],
      "services": ["Porta Potties", "Dumpsters", "Restroom Trailers", "Handicap Units"],
      "pros": ["One-stop shop", "Combo packages available", "Time and cost savings"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "sandy-springs-quick-relief",
      "name": "Quick Relief Solutions",
      "city": "sandy-springs",
      "rating": 4.7,
      "reviewCount": 118,
      "phone": "(404) 555-0100",
      "location": "Sandy Springs, GA",
      "hours": "Mon-Sun: 7:00 AM - 7:00 PM",
      "website": "https://quickreliefsolutions.com",
      "badges": ["Spanish-Speaking Team"],
      "services": ["Standard Porta Potties", "ADA Units", "Handwashing Stations", "Luxury Trailers"],
      "pros": ["Spanish-speaking team", "Rigorously inspected", "Climate-controlled trailers"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "sandy-springs-atlanta-porta-potty",
      "name": "Atlanta Porta Potty Rental",
      "city": "sandy-springs",
      "rating": 4.6,
      "reviewCount": 55,
      "phone": "(678) 750-4144",
      "location": "Sandy Springs, GA",
      "hours": "Mon-Fri: 8:00 AM - 6:00 PM",
      "website": "https://www.atlantaportapotty.com/sandy-springs-rental",
      "badges": [],
      "services": ["Standard Units", "Deluxe Units", "ADA-Accessible", "Luxury Trailers"],
      "pros": ["Free quotes", "Fast service", "Professional"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "sandy-springs-porta-potty-dogs",
      "name": "Porta Potty Dogs",
      "city": "sandy-springs",
      "rating": 4.6,
      "reviewCount": 78,
      "phone": "(678) 408-4056",
      "location": "Sandy Springs, GA",
      "hours": "Mon-Fri: 8:00 AM - 5:00 PM",
      "website": "https://www.portapottydogs.com",
      "badges": [],
      "services": ["Portable Toilets", "Dumpsters", "Storage", "Fencing"],
      "pros": ["Multiple services", "Top-tier equipment", "Excellent service"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "sandy-springs-porta-potty-pro",
      "name": "Porta Potty Pro",
      "city": "sandy-springs",
      "rating": 4.8,
      "reviewCount": 143,
      "phone": "(888) 880-7713",
      "location": "Sandy Springs, GA",
      "hours": "Mon-Sun: 7:00 AM - 7:00 PM",
      "website": "https://portabletoiletssandyspringsga.com",
      "badges": ["Decades of Experience"],
      "services": ["Standard Units", "Flushing Units", "ADA Units", "Restroom Trailers"],
      "pros": ["Decades of experience", "Flat-rate pricing", "No hidden fees"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "sandy-springs-porta-potty-rentals-pros",
      "name": "Porta Potty Rentals Pros",
      "city": "sandy-springs",
      "rating": 4.5,
      "reviewCount": 67,
      "phone": "(833) 618-0156",
      "location": "Sandy Springs, GA",
      "hours": "Mon-Fri: 8:00 AM - 6:00 PM",
      "website": "https://sandy-springs-ga.jandjdumpstersolutionsllc.com",
      "badges": [],
      "services": ["Construction Units", "Wedding Units", "Event Restrooms", "Roll-Off Dumpsters"],
      "pros": ["Free transparent quotes", "No hidden fees", "Fast delivery"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "sandy-springs-porta-potty-rental-duluth",
      "name": "Porta Potty Rental",
      "city": "sandy-springs",
      "rating": 4.4,
      "reviewCount": 53,
      "phone": "(678) 399-8890",
      "location": "Sandy Springs, GA",
      "hours": "Mon-Fri: 8:00 AM - 6:00 PM",
      "website": "https://portapottyrentalduluth.com",
      "badges": [],
      "services": ["Standard Units", "Event Rentals", "Construction Sites"],
      "pros": ["Thorough cleaning", "On-time delivery", "Well-maintained units"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "sandy-springs-americas-portable",
      "name": "America's Portable Toilets",
      "city": "sandy-springs",
      "rating": 4.6,
      "reviewCount": 74,
      "phone": "(870) 306-3280",
      "location": "Sandy Springs, GA",
      "hours": "Mon-Fri: 8:00 AM - 6:00 PM",
      "website": "https://americasportabletoilets.com",
      "badges": [],
      "services": ["Portable Restrooms", "Porta Potties", "Restroom Trailers"],
      "pros": ["Comfort built-in", "Dependable", "Large crowd management"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "johns-creek-patriot-portables",
      "name": "Patriot Portables",
      "city": "johns-creek",
      "rating": 5,
      "reviewCount": 127,
      "phone": "(678) 456-3488",
      "location": "Cumming, GA (Serves Johns Creek)",
      "hours": "Mon-Sun: 7:00 AM - 7:00 PM",
      "website": "https://patriotportables.com",
      "badges": ["Same-Day Delivery", "Woman-Owned"],
      "services": ["Standard Porta Potties", "Deluxe Units", "ADA Compliant", "Luxury Trailers"],
      "pros": ["Same-day delivery", "Sparkling clean", "Professional service"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "johns-creek-quick-relief",
      "name": "Quick Relief Solutions",
      "city": "johns-creek",
      "rating": 4.7,
      "reviewCount": 118,
      "phone": "(404) 555-0100",
      "location": "Johns Creek, GA",
      "hours": "Mon-Sun: 7:00 AM - 7:00 PM",
      "website": "https://quickreliefsolutions.com",
      "badges": ["Spanish-Speaking Team"],
      "services": ["Standard Units", "ADA Units", "Handwashing Stations", "Luxury Trailers"],
      "pros": ["Bilingual team", "Flexible rentals", "Rigorously inspected"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "duluth-patriot-portables",
      "name": "Patriot Portables",
      "city": "duluth",
      "rating": 5,
      "reviewCount": 127,
      "phone": "(678) 456-3488",
      "location": "Cumming, GA (Serves Duluth)",
      "hours": "Mon-Sun: 7:00 AM - 7:00 PM",
      "website": "https://patriotportables.com",
      "badges": ["Same-Day Delivery", "Woman-Owned"],
      "services": ["Standard Porta Potties", "Deluxe Units", "ADA Compliant", "Luxury Trailers"],
      "pros": ["Same-day delivery", "10-point inspection", "Always answers phone"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "duluth-quick-relief",
      "name": "Quick Relief Solutions",
      "city": "duluth",
      "rating": 4.7,
      "reviewCount": 118,
      "phone": "(404) 555-0100",
      "location": "Duluth, GA",
      "hours": "Mon-Sun: 7:00 AM - 7:00 PM",
      "website": "https://quickreliefsolutions.com",
      "badges": ["Spanish-Speaking Team"],
      "services": ["Standard Units", "ADA Units", "Handwashing Stations", "Luxury Trailers"],
      "pros": ["Spanish-speaking staff", "Clean units", "Reliable service"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "lawrenceville-patriot-portables",
      "name": "Patriot Portables",
      "city": "lawrenceville",
      "rating": 5,
      "reviewCount": 127,
      "phone": "(678) 456-3488",
      "location": "Cumming, GA (Serves Lawrenceville)",
      "hours": "Mon-Sun: 7:00 AM - 7:00 PM",
      "website": "https://patriotportables.com",
      "badges": ["Same-Day Delivery", "Woman-Owned"],
      "services": ["Standard Porta Potties", "Deluxe Units", "ADA Compliant", "Luxury Trailers"],
      "pros": ["Same-day delivery", "Professional team", "Veteran-supported"],
      "cons": [],
      "reviews": []
    },
    {
      "id": "lawrenceville-quick-relief",
      "name": "Quick Relief Solutions",
      "city": "lawrenceville",
      "rating": 4.7,
      "reviewCount": 118,
      "phone": "(404) 555-0100",
      "location": "Lawrenceville, GA",
      "hours": "Mon-Sun: 7:00 AM - 7:00 PM",
      "website": "https://quickreliefsolutions.com",
      "badges": ["Spanish-Speaking Team"],
      "services": ["Standard Units", "ADA Units", "Handwashing Stations", "Luxury Trailers"],
      "pros": ["Bilingual service", "Premium finishes on luxury units", "Reliable"],
      "cons": [],
      "reviews": []
    }
  ]
};

module.exports = async function handler(req, res) {
  // CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  try {
    if (req.method === 'GET') {
      // Try to get from Blob storage first
      try {
        const blobResult = await head(BLOB_STORE_NAME, {
          token: process.env.BLOB_READ_WRITE_TOKEN
        });

        if (blobResult && blobResult.url) {
          const response = await fetch(blobResult.url);
          const data = await response.json();
          return res.status(200).json(data);
        }
      } catch (error) {
        console.log('No blob found or error fetching blob, using default data:', error.message);
      }

      // If blob doesn't exist or error, return default data
      return res.status(200).json(DEFAULT_DATA);

    } else if (req.method === 'POST') {
      // Save data to Blob storage
      const data = req.body;

      const blob = await put(BLOB_STORE_NAME, JSON.stringify(data), {
        access: 'public',
        token: process.env.BLOB_READ_WRITE_TOKEN,
        addRandomSuffix: false,
        contentType: 'application/json'
      });

      return res.status(200).json({ 
        success: true, 
        url: blob.url,
        message: 'Data saved successfully'
      });
    } else {
      res.status(405).json({ error: 'Method not allowed' });
    }
  } catch (error) {
    console.error('API Error:', error);
    res.status(500).json({ 
      error: 'Server error',
      message: error.message 
    });
  }
};
